#!/usr/bin/python3

import os

csfml = input("Select Project:\n1: CSFML\n2: Basic")
name = input("Select Name of binary:")

MakeFile1:str = """##
## EPITECH PROJECT, 2022
## Base MakeFile
## File description:
## Makefile
##

SRC			=	src/{}.c

MAIN 		=	main.c

MAIN_OBJ 	=	$(MAIN:.c=.o)

SRC_OBJ 	= 	$(SRC:.c=.o)

NAME		=	{}

CPPFLAGS 	=	-I ./include -W -Wall -Wextra -O2

LIBCSFML	=	-lcsfml-graphics -lcsfml-system -lcsfml-audio

all:		$(NAME)

$(NAME): $(MAIN_OBJ) $(SRC_OBJ)
	gcc -o $(NAME) $(SRC_OBJ) $(MAIN_OBJ) $(LIBCSFML) $(CPPFLAGS)

clean:
	rm -f *~
	rm -f *#
	rm -f *.o
	rm -f src/*.o
	rm -f a.out

fclean: clean
	rm -f $(NAME)

re: fclean all

run: re
	make clean
	./$(NAME)

debug: CPPFLAGS += -g
debug: re

.PHONY: all clean fclean re run debug""".format(name, name)

MakeFile2:str = """##
## EPITECH PROJECT, 2022
## Base MakeFile
## File description:
## Makefile
##

SRC			=	src/{}.c

MAIN 		=	main.c

MAIN_OBJ 	=	$(MAIN:.c=.o)

SRC_OBJ 	= 	$(SRC:.c=.o)

NAME		=	{}

CPPFLAGS 	=	-I ./include -W -Wall -Wextra -O2

all:		$(NAME)

$(NAME): $(MAIN_OBJ) $(SRC_OBJ)
	gcc -o $(NAME) $(SRC_OBJ) $(MAIN_OBJ) $(CPPFLAGS)

clean:
	rm -f *~
	rm -f *#
	rm -f *.o
	rm -f src/*.o
	rm -f a.out

fclean: clean
	rm -f $(NAME)

re: fclean all

run: re
	make clean
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo ""
	@-echo "------------------------ Running $(NAME) ------------------------"
	./$(NAME)

debug: CPPFLAGS += -g
debug: re

.PHONY: all clean fclean re run debug""".format(name, name)



Include1:str = """/*
** EPITECH PROJECT, 2022
** Base Include
** File description:
** {}
*/

#ifndef {}_H_
    #define {}_H_

    #include <SFML/System.h>
    #include <SFML/Graphics.h>
    #include <stddef.h>
    #include <SFML/Audio.h>
    #include <unistd.h>
    #include <stdlib.h>
    #include <stdio.h>
    #include <sys/types.h>
    #include <sys/stat.h>
    #include <fcntl.h>

int {}(int args, char **arg);

#endif /* !{}_H_ */""".format(name, name.upper(), name.upper(), name, name.upper())

Include2:str = """/*
** EPITECH PROJECT, 2022
** Base Include
** File description:
** {}
*/

#ifndef {}_H_
    #define {}_H_

    #include <stddef.h>
    #include <unistd.h>
    #include <stdlib.h>
    #include <stdio.h>
    #include <sys/types.h>
    #include <sys/stat.h>
    #include <fcntl.h>

int {}(int args, char **arg);

#endif /* !{}_H_ */""".format(name, name.upper(), name.upper(), name, name.upper())

gitignore_str:str = """{}
.vscode
*.o
*.a
.gc*""".format(name)

main_str:str = """/*
** EPITECH PROJECT, 2022
** Base Main
** File description:
** {} main file
*/

#include "{}.h"

int main(int ac, char **av, char **env)
{{
    return 0;
}}
""".format(name, name)

project_str:str = """/*
** EPITECH PROJECT, 2022
** Base Project file
** File description:
** {} project file
*/

#include "{}.h"

int {}(int args, char **arg)
{{
    return 0;
}}
""".format(name, name, name)

readme_str:str = """<h1 align="center">
  <br>
  {}
  <br>
</h1>

<h4 align="center">Epitech Project PROMO 2026: {}</h4>
""".format(name, name)

os.mkdir("include")
os.mkdir("src")

MakeFile = open("Makefile", "w")
Include = open("include/{}.h".format(name), "w")
Main = open("main.c".format(name), "w")
Project = open("src/{}.c".format(name), "w")
GitIgnore = open(".gitignore", "w")
Readme = open("ReadMe.md", "w")
if csfml == "1":
    MakeFile.write(MakeFile1)
    Include.write(Include1)
if csfml == "2":
    MakeFile.write(MakeFile2)
    Include.write(Include2)
GitIgnore.write(gitignore_str)
Readme.write(readme_str)
Main.write(main_str)
Project.write(project_str)
os.system("git add Makefile")
os.system("""git commit -m "[ADD] Basic MakeFile" """)
os.system("git add include")
os.system("""git commit -m "[ADD] Basic Include" """)
os.system("git add .gitignore")
os.system("""git commit -m "[ADD] Basic GitIgnore" """)
os.system("git add main.c")
os.system("""git commit -m "[ADD] Basic main.c" """)
os.system("git add src")
os.system("""git commit -m "[ADD] Basic source files" -m "Added Basic {}.c" """.format(name))
os.system("git add ReadMe.md")
os.system("""git commit -m "[ADD] Basic ReadMe" """)
os.system("git push")
